Skip creating civil date for dates that have 00 as day or month
Date.civil can't handle dates where month and/or day is set to 00

```
irb(main):001:0> require "date"
=> true
irb(main):002:0> Date.civil(0000,00,00)
ArgumentError: invalid date
	from (irb):2:in `civil'
	from (irb):2
	from /Users/sergeym/.rbenv/versions/2.1.2/bin/irb:11:in `<main>'
irb(main):003:0> Date.civil(0000,01,00)
ArgumentError: invalid date
	from (irb):3:in `civil'
	from (irb):3
	from /Users/sergeym/.rbenv/versions/2.1.2/bin/irb:11:in `<main>'
irb(main):004:0> Date.civil(0000,00,01)
ArgumentError: invalid date
	from (irb):4:in `civil'
	from (irb):4
	from /Users/sergeym/.rbenv/versions/2.1.2/bin/irb:11:in `<main>'
irb(main):005:0> Date.civil(0001,00,00)
ArgumentError: invalid date
	from (irb):5:in `civil'
	from (irb):5
	from /Users/sergeym/.rbenv/versions/2.1.2/bin/irb:11:in `<main>'
irb(main):006:0> Date.civil(0001,01,01)
=> #<Date: 0001-01-01 ((1721424j,0s,0n),+0s,2299161j)>
irb(main):007:0>
```